## Python для анализа данных
### Домашнее задание NumPy

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [5]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [116]:
scores[scores == 0].size

13

### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [115]:
scores[scores > 50].size

64

### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [117]:
scores[(scores >= 50) & (scores <= 70) ].size

26

### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [108]:
scores.mean(axis = 0).argmax()

8

### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. 

In [39]:
nonzero = scores[scores>0]
print(nonzero)

[ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл среди всех групп.

In [41]:
nonzero.min()

1

### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. 

In [42]:
advanced = nonzero[nonzero > 80]
print(advanced)

[ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
  88 100  86  96 100  98  87 100  88  89]


### Задание 8

Получить из исходного массива `scores` массив медианных оценок по группам.

In [109]:
np.median(scores, axis = 1)

array([26. , 61.5, 66. , 49. , 46.5, 30. , 54. , 43. , 28. , 63. , 22. ,
       45.5, 22. , 54.5, 39.5])

### Задание 9

Перераспределить студентов из `scores` в 10 групп по 15 человек с помощью метода `reshape`. Посчитать среднюю оценку в группе на обновленных данных.

In [114]:
print(scores.reshape(10, 15))
scores.reshape(10, 15).mean(axis = 1)

[[ 20  40  56  80   0   5  25  27  74   1   0  98  67 100   8]
 [ 56  34  82 100   7  78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77  90  87  41  89  52]
 [  0   5  17  28  99  32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100  77  28  39  41   0]
 [ 81  45  54  98  12  66   0  88   0  44   0  55 100  12  11]
 [ 17  70  86  96  56  23  32  49  70  80  20  24  76  50  29]
 [ 40   3   2   5  11  33  63  28  40  51 100  98  87  22  30]
 [ 16  54  78  12  25  35  10  19  67   0 100  88  24  33  47]
 [ 56  62  34  77  53  50  89  70  72  56  29  15  20   0   0]]


array([40.06666667, 55.53333333, 60.8       , 33.73333333, 47.93333333,
       44.4       , 51.86666667, 40.86666667, 40.53333333, 45.53333333])

### Задание 10

Определить общее число элементов в массиве `advanced`.

In [49]:
advanced.size

28

### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [54]:
sto = (scores == 100)
print(sto)

[[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]]


### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [56]:
scores[:7]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])